server:
    port: 8084

eureka:
  client:
    fetch-registry: true  # Fetch the registry from the Eureka server
    register-with-eureka: true  # Register this config server with Eureka
    service-url:
      defaultZone: http://localhost:8082/eureka/
